# FROM public.ecr.aws/lambda/python:3.12

# WORKDIR /

# RUN ln -sf python3 /usr/bin/python
# # install latest version of pip rather than the older OS one.
# RUN wget -q https://bootstrap.pypa.io/get-pip.py
# RUN python3 /get-pip.py
# RUN python -m pip install --upgrade pip
# RUN rm -f /get-pip.py
# COPY . .
# RUN python3 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

### TRY THIS CODE INSTEAD

FROM public.ecr.aws/lambda/python:3.14@sha256:68c03c299a73a1bba0cb99d7395954404a484161e2bb996dd6b6ef80126983b3

COPY index.py ${LAMBDA_TASK_ROOT}

COPY requirements.txt ${LAMBDA_TASK_ROOT}

COPY utils/ ${LAMBDA_TASK_ROOT}/utils/

RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# RUN ls -la ${LAMBDA_TASK_ROOT}/*

CMD [ "index.handler" ]
# CMD [ "index.lambda_handler" ]
