[pytest]
pythonpath = src
addopts = -p no:socket
markers =
    e2e: runs end-to-end tests against real AWS/MarkLogic resources
env =
    SOURCE_BUCKET=TEST_SOURCE_BUCKET
    API_USERNAME=TEST_USERNAME
    API_PASSWORD=TEST_PASSWORD
    ENVIRONMENT=TEST_ENVIRONMENT
