FROM public.ecr.aws/lambda/python:3.9

WORKDIR /

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y wget software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3-distutils python3.9

RUN ln -sf python3 /usr/bin/python
# install latest version of pip rather than the older OS one.
RUN wget -q https://bootstrap.pypa.io/get-pip.py
RUN python /get-pip.py
RUN python -m pip install --upgrade pip
RUN rm -f /get-pip.py
COPY . .
RUN python3 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
