# FROM public.ecr.aws/lambda/python:3.9

# WORKDIR /

# RUN yum -y upgrade
# RUN yum -y install wget

# RUN ln -sf python3 /usr/bin/python
# # install latest version of pip rather than the older OS one.
# RUN wget -q https://bootstrap.pypa.io/get-pip.py
# RUN python /get-pip.py
# RUN python -m pip install --upgrade pip
# RUN rm -f /get-pip.py

# COPY . .
# RUN python3 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# RUN ls -la ${LAMBDA_TASK_ROOT}/*

# CMD ["index.handler"]

### TRY THIS CODE INSTEAD

FROM public.ecr.aws/lambda/python:3.9
# FROM public.ecr.aws/lambda/python:3.8
# Using AWS lambda image for Python 3.6 that can use the pre-built postgress driver library
# FROM lambci/lambda:build-python3.6
# FROM public.ecr.aws/lambda/python:3.6

COPY index.py ${LAMBDA_TASK_ROOT}

COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

RUN ls -la ${LAMBDA_TASK_ROOT}/*

CMD [ "index.handler" ]
# CMD [ "index.lambda_handler" ]
