# FROM public.ecr.aws/lambda/python:3.12

# WORKDIR /

# RUN ln -sf python3 /usr/bin/python
# # install latest version of pip rather than the older OS one.
# RUN wget -q https://bootstrap.pypa.io/get-pip.py
# RUN python /get-pip.py
# RUN python -m pip install --upgrade pip
# RUN rm -f /get-pip.py
# COPY . .
# RUN python3 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

### TRY THIS CODE INSTEAD

FROM public.ecr.aws/lambda/python:3.12@sha256:d2ea26e3be8697c73989dd8a0ab3f05f004b7bb99fc1b9fd27258290940fbfa5

COPY index.py ${LAMBDA_TASK_ROOT}

COPY requirements.txt ${LAMBDA_TASK_ROOT}
COPY utils/ ${LAMBDA_TASK_ROOT}/utils/

RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# RUN ls -la ${LAMBDA_TASK_ROOT}/*

CMD [ "index.handler" ]
# CMD [ "index.lambda_handler" ]
