name: Deploy to Staging then Prod

on:
  push:
    branches:
      - main

permissions:
  pull-requests: read
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy_staging:
    name: Deploy Staging Build
    uses: ./.github/workflows/deploy_single_environment.yml
    secrets:
      aws_oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      account_id: ${{ secrets.STAGING_ACCOUNT_ID }}
      workspace: tna-staging
      app_env: staging

  deploy_production:
    name: Deploy Production Build
    uses: ./.github/workflows/deploy_single_environment.yml
    needs: deploy_staging
    secrets:
      aws_oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_ARN_PROD }}
      account_id: ${{ secrets.PROD_ACCOUNT_ID }}
      workspace: tna-prod
      app_env: production
