name: Deploy to Staging then Prod

on:
  push:
    branches:
      - main

permissions:
  pull-requests: read
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  staging_apply:
    name: Deploy Staging Build
    uses: ./.github/workflows/deploy_single_environment.yml
    secrets:
      account_id: ${{ secrets.STAGING_ACCOUNT_ID }}
      workspace: tna-staging
      app_env: staging


  prod_apply:
    name: Deploy Production Build
    uses: ./.github/workflows/deploy_single_environment.yml
    needs: staging_apply
    secrets:
      account_id: ${{ secrets.PROD_ACCOUNT_ID }}
      workspace: tna-prod
      app_env: production
