name: CI tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write
  id-token: write
  contents: read
  issues: write

defaults:
  run:
    shell: bash

jobs:
  lint-and-test_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v2.0.1
        with:
          tflint_version: v0.38.1
        continue-on-error: false

      - name: Run TFLint
        id: run_tflint
        run: |
          tflint --init
          tflint -f compact --loglevel warn

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        continue-on-error: false

      - name: Get Production AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        continue-on-error: false

      - name: Terraform init Prod
        id: run_tf_init_prod
        run: |
          set +e
          set +o pipefail
          terraform init -upgrade -input=false -backend-config="bucket=tna-terraform-backend-state-enrichment-pipeline-${{ secrets.PROD_ACCOUNT_ID}}"
        continue-on-error: false

      - name: Terraform Plan Prod
        id: run_tf_plan_prod
        run: |
          set +e
          set +o pipefail
          terraform workspace select tna-prod
          terraform plan -no-color -var "app_env=prod"
