on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      aws_oidc_role_arn:
        required: true
      account_id:
        required: true
      workspace:
        required: true
      app_env:
        required: true

jobs:
  deploy_single_environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.sha }}
          persist-credentials: false

      - name: Set up Python 3.13
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.aws_oidc_role_arn }}
        continue-on-error: false

      - name: Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          install: true

      - name: Assemble Lambdas
        run: |
          set -e
          set -o pipefail
          ./scripts/assemble_lambda_contexts.sh

      - name: Get terraform version
        id: get-terraform-version
        run: |
          DOTFILE_VERSION=$(cat terraform/.terraform-version)
          echo "version=$DOTFILE_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        continue-on-error: false
        with:
          terraform_version: ${{ steps.get-terraform-version.outputs.version }}

      - name: Terraform init
        run: |
          set -e
          set -o pipefail
          cd terraform
          terraform init -upgrade -input=false -backend-config="bucket=tna-terraform-backend-state-enrichment-pipeline-${{ secrets.account_id }}"
          terraform workspace list
        continue-on-error: false

      - name: Terraform Apply
        run: |
          set -e
          set -o pipefail
          cd terraform
          terraform workspace select ${{ secrets.workspace }}
          terraform apply --auto-approve -no-color -var "app_env=${{ secrets.app_env }}"

      # Pushing images to ECR last
      - name: Build Docker Images For Lambda
        run: |
          set -e
          set -o pipefail

          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com

          ## ENRICHMENT (consolidated pipeline)
          make build-lambda LAMBDA=enrichment_lambda ASSEMBLED=1
          docker tag enrichment_lambda:local ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-enrichment-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-enrichment-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-enrichment --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-enrichment-${{ secrets.app_env }}:latest

          ## DB_BACKUP
          make build-lambda LAMBDA=db_backup ASSEMBLED=1
          docker tag db_backup:local ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-db-backup --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest

          ## UPDATE_LEGISLATION_TABLE
          make build-lambda LAMBDA=update_legislation_table ASSEMBLED=1
          docker tag update_legislation_table:local ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-update-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-update-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-update-legislation-table --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-update-${{ secrets.app_env }}:latest

          ## UPDATE_RULES_PROCESSOR
          make build-lambda LAMBDA=update_rules_processor ASSEMBLED=1
          docker tag update_rules_processor:local ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-update-rules-processor --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
