on:
  workflow_call:
    secrets:
      aws_oidc_role_arn:
        required: true
      account_id:
        required: true
      workspace:
        required: true
      app_env:
        required: true

jobs:
  deploy_single_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.aws_oidc_role_arn }}
        continue-on-error: false

      - name: Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          install: true

      - name: Assemble Lambdas
        run: |
          set -e
          set -o pipefail

          cd src/


          ###################################
          ## DETERMINE_LEGISLATION_PROVISIONS

          mkdir lambdas/determine_legislation_provisions/legislation_provisions_extraction
          cp -r legislation_provisions_extraction/*.* lambdas/determine_legislation_provisions/legislation_provisions_extraction/
          cp legislation_provisions_extraction/requirements.txt lambdas/determine_legislation_provisions/

          mkdir lambdas/determine_legislation_provisions/replacer
          cp -r replacer/*.py lambdas/determine_legislation_provisions/replacer/

          mkdir lambdas/determine_legislation_provisions/utils
          cp -r utils/*.py lambdas/determine_legislation_provisions/utils/


          ###############################
          ## DETERMINE_OBLIQUE_REFERENCES

          mkdir lambdas/determine_oblique_references/oblique_references
          cp -r oblique_references/*.* lambdas/determine_oblique_references/oblique_references/
          cp oblique_references/requirements.txt lambdas/determine_oblique_references/

          mkdir lambdas/determine_oblique_references/replacer
          cp -r replacer/*.py lambdas/determine_oblique_references/replacer/

          mkdir lambdas/determine_oblique_references/utils
          cp -r utils/*.py lambdas/determine_oblique_references/utils/


          #######################################
          ## DETERMINE_REPLACEMENTS_ABBREVIATIONS

          mkdir lambdas/determine_replacements_abbreviations/abbreviation_extraction
          cp -r abbreviation_extraction/*.* lambdas/determine_replacements_abbreviations/abbreviation_extraction/
          cp abbreviation_extraction/requirements.txt lambdas/determine_replacements_abbreviations/

          mkdir lambdas/determine_replacements_abbreviations/utils
          cp -r utils/*.py lambdas/determine_replacements_abbreviations/utils/


          #################################
          ## DETERMINE_REPLACEMENTS_CASELAW

          mkdir lambdas/determine_replacements_caselaw/caselaw_extraction
          cp -r caselaw_extraction/*.py lambdas/determine_replacements_caselaw/caselaw_extraction/
          cp caselaw_extraction/requirements.txt lambdas/determine_replacements_caselaw/requirements.txt

          mkdir lambdas/determine_replacements_caselaw/rules
          # cp caselaw_extraction/rules/citation_patterns.jsonl lambdas/determine_replacements_caselaw/rules/citation_patterns.jsonl
          # cp citation_patterns.jsonl lambdas/determine_replacements_caselaw/
          # dragon: the first of these was commented out, but could copy a file. The second cannot...
          # but we need a citations_patterns.json  in the root lambda directory, so let's make a chimera.
          cp caselaw_extraction/rules/citation_patterns.jsonl lambdas/determine_replacements_caselaw/

          mkdir lambdas/determine_replacements_caselaw/database
          cp -r database/*.py lambdas/determine_replacements_caselaw/database/

          mkdir lambdas/determine_replacements_caselaw/utils
          cp -r utils/*.py lambdas/determine_replacements_caselaw/utils/


          #####################################
          ## DETERMINE_REPLACEMENTS_LEGISLATION

          mkdir lambdas/determine_replacements_legislation/legislation_extraction
          cp -r legislation_extraction/*.* lambdas/determine_replacements_legislation/legislation_extraction/
          cp legislation_extraction/requirements.txt lambdas/determine_replacements_legislation/

          mkdir lambdas/determine_replacements_legislation/utils
          cp -r utils/*.py lambdas/determine_replacements_legislation/utils/

          mkdir lambdas/determine_replacements_legislation/database
          cp -r database/*.py lambdas/determine_replacements_legislation/database/


          #############################
          ## EXTRACT_JUDGEMENT_CONTENTS

          mkdir lambdas/extract_judgement_contents/utils
          cp -r utils/*.py lambdas/extract_judgement_contents/utils/


          ############
          ## FETCH_XML

          mkdir lambdas/fetch_xml/utils
          cp -r utils/*.py lambdas/fetch_xml/utils/


          ####################
          ## MAKE_REPLACEMENTS

          mkdir -p lambdas/make_replacements/utils
          cp -r utils/*.py lambdas/make_replacements/utils/

          mkdir -p lambdas/make_replacements/replacer
          cp -r replacer/*.py lambdas/make_replacements/replacer/


          ###########################
          ## UPDATE_LEGISLATION_TABLE

          mkdir lambdas/update_legislation_table/utils
          cp -r utils/*.py lambdas/update_legislation_table/utils/

          mkdir lambdas/update_legislation_table/database
          cp -r database/*.py lambdas/update_legislation_table/database/


          #########################
          ## UPDATE_RULES_PROCESSOR

          mkdir lambdas/update_rules_processor/utils
          cp -r utils/*.py lambdas/update_rules_processor/utils/

          mkdir lambdas/update_rules_processor/database
          cp -r database/*.py lambdas/update_rules_processor/database/


          ###############
          ## XML_VALIDATE

          mkdir lambdas/xml_validate/utils
          cp -r utils/*.py lambdas/xml_validate/utils/


          ###############
          ## PUSH_ENRICHED_XML

          mkdir lambdas/push_enriched_xml/utils
          cp -r utils/*.py lambdas/push_enriched_xml/utils/


          ## PUSH_XML

          mkdir -p lambdas/push_enriched_xml/utils
          cp -r utils/*.py lambdas/push_enriched_xml/utils/

          cd "${GITHUB_WORKSPACE}"

      - name: Get terraform version
        id: get-terraform-version
        run: |
          DOTFILE_VERSION=$(cat terraform/.terraform-version)
          echo "version=$DOTFILE_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        continue-on-error: false
        with:
          terraform_version: ${{ steps.get-terraform-version.outputs.version }}

      - name: Terraform init
        run: |
          set -e
          set -o pipefail
          cd terraform
          terraform init -upgrade -input=false -backend-config="bucket=tna-terraform-backend-state-enrichment-pipeline-${{ secrets.account_id }}"
          terraform workspace list
        continue-on-error: false

      - name: Terraform Apply
        run: |
          set -e
          set -o pipefail
          cd terraform
          terraform workspace select ${{ secrets.workspace }}
          terraform apply --auto-approve -no-color -var "app_env=${{ secrets.app_env }}"

      # Pushing images to ECR last
      - name: Build Docker Images For Lambda
        run: |
          set -e
          set -o pipefail

          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com


          ############
          ## DB_BACKUP

          cd "src/lambdas/db_backup"
          docker buildx build --load -t tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-db-backup --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-db-backup-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          ###################################
          ## DETERMINE_LEGISLATION_PROVISIONS

          cd "src/lambdas/determine_legislation_provisions"
          docker buildx build --load -t tna-s3-tna-ecr-repository-legislation-provision-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-legislation-provision-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-provision-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-provision-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-determine-legislation-provisions --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-provision-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          ###############################
          ## DETERMINE_OBLIQUE_REFERENCES

          cd "src/lambdas/determine_oblique_references"
          docker buildx build --load -t tna-s3-tna-ecr-repository-oblique-references-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-oblique-references-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-oblique-references-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-oblique-references-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-determine-oblique-references --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-oblique-references-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          #######################################
          ## DETERMINE_REPLACEMENTS_ABBREVIATIONS

          cd "src/lambdas/determine_replacements_abbreviations"
          docker buildx build --load -t tna-s3-tna-ecr-repository-abbreviations-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-abbreviations-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-abbreviations-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-abbreviations-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-determine-replacements-abbreviations --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-abbreviations-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          #################################
          ## DETERMINE_REPLACEMENTS_CASELAW

          cd "src/lambdas/determine_replacements_caselaw"
          docker buildx build --load -t tna-s3-tna-ecr-repository-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-determine-replacements-caselaw --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          #####################################
          ## DETERMINE_REPLACEMENTS_LEGISLATION

          cd "src/lambdas/determine_replacements_legislation"
          docker buildx build --load -t tna-s3-tna-ecr-repository-legislation-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-legislation-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-determine-replacements-legislation --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          ############
          ## FETCH_XML

          cd "src/lambdas/fetch_xml"
          docker buildx build --load -t tna-s3-tna-ecr-repository-fetch-xml-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-fetch-xml-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-fetch-xml-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-fetch-xml-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-fetch-xml --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-fetch-xml-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          ####################
          ## PUSH_ENRICHED_XML

          cd "src/lambdas/push_enriched_xml"
          docker buildx build --load -t tna-s3-tna-ecr-repository-push-enriched-xml-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-push-enriched-xml-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-push-enriched-xml-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-push-enriched-xml-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-push-enriched-xml --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-push-enriched-xml-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"


          #########################
          ## UPDATE_RULES_PROCESSOR

          cd "src/lambdas/update_rules_processor"
          docker buildx build --load -t tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }} .
          docker tag tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
          docker push ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
          aws lambda update-function-code --function-name tna-s3-tna-${{ secrets.app_env }}-update-rules-processor --image-uri ${{ secrets.account_id }}.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-rules-update-${{ secrets.app_env }}:latest
          cd "${GITHUB_WORKSPACE}"
