name: "Apply Production Terraform"

on:
  push:
    branches:
      - main

permissions:
  pull-requests: read
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  prod_terraform:
    needs: [ staging_build, staging_terraform, prod_build ]
    runs-on: ubuntu-latest

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        continue-on-error: false

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY_PROD }}
        continue-on-error: false

      - name: Terraform init
        run: |
          set +e
          set +o pipefail
          terraform init -upgrade -input=false -backend-config="bucket=tna-terraform-backend-state-enrichment-pipeline-${{ secrets.PROD_ACCOUNT_ID}}"
        continue-on-error: false

      - name: Terraform Plan
        run: |
          set +e
          set +o pipefail
          terraform workspace select tna-prod
          terraform plan -no-color -var "app_env=production"

      - name: Terraform Apply
        run: |
          set +e
          set +o pipefail
          terraform workspace select tna-prod
          terraform apply --auto-approve -no-color -var "app_env=prod"
